{{- if .Values.OpenServiceMesh.enableFluentbit }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-configmap
  namespace: {{.Values.OpenServiceMesh.namespace}}
data:
  fluent-bit.conf: |-
    [SERVICE]
      Flush             5
      Daemon            off
      Log_Level         debug
      Parsers_File      parser.conf
    [INPUT]
      Name    tail
      Tag     kube.*
      Path    /var/log/containers/osm-controller-*_{{.Values.OpenServiceMesh.namespace}}_osm-controller-*.log
      Parser  cri
    [FILTER]
      Name           modify
      Match          kube.*
      # Condition      Key_value_matches message /"level":"info"/
      Condition      Key_value_matches level "info"
      Set            keep true
    [FILTER]
      Name           modify
      Match          kube.*
      Condition      Key_value_matches log \\"level\\":\\"info\\"
      Set            keep true
    [FILTER]
      Name           grep
      Match          kube.*
      Regex          keep true
    # [FILTER]
    #   name       grep
    #   match      *
    #   regex     $log['log']['level'] info
      # regex     $log['log'] \\"level\\":\\"error\\"
      # regex     message /"level":"info"/
      # regex   log info
    [OUTPUT]
      Name    stdout
      match   *  
    [OUTPUT]
      Name        azure
      Match       *
      Customer_ID 42b0f26b-f8f7-4aa9-9222-25c68b665e62
      Shared_Key  u+A5O47P06AURgONYCjThezYMBov7oESLoir5gMFjLCgJPdRHdgis7Ux8ytgaibbkwCDzIIzEdo9oWkSWlORvA==
  parser.conf: |-
    [PARSER]
      # http://rubular.com/r/tjUt3Awgg4
      Name    cri
      Format  regex
      Regex   ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z
{{- end }}
